// <auto-generated />
using BusApiProyect.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusApiProyect.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250120020241_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusApiProyect.Data.Models.User", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("_is_admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
